version: '3.3'
services:
  backend:
    build:
      context: .
    command: npm run start:dev
    container_name: progig-backend
    env_file: /home/azureuser/environments/.env.production
    ports:
      - '80:3010'
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
