version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm run start:prod
    container_name: progig-backend
    env_file: /home/azureuser/environments/.env.production
    ports:
      - '80:3000'
    volumes:
      - /usr/src/app/node_modules
