version: '3.3'
services:
  backend:
    build:
      context: .
      target: development
    command: npm run start:dev
    container_name: progig-backend
    env_file: /home/azureuser/environments/.env
    depends_on:
      - postgres
    ports:
      - '80:3010'
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules

  postgres:
    image: 'postgres:13'
    container_name: progig-postgres
    ports:
      - '5432:5432'
    env_file: /home/azureuser/environments/.env
    volumes:
      - /home/azureuser/appdata/postgres:/var/lib/postgresql/data/:rw
