version: '3.3'
services:
  backend:
    build:
      context: .
      target: development
    command: npm run start:dev
    container_name: progig-backend
    env_file: /home/azureuser/environments/.env
    # depends_on:
    # - postgres
    # - mysql
    ports:
      - '80:3010'
    volumes:
      - progig-backend:/usr/src/app
      - /usr/src/app/node_modules

  # postgres:
  #   image: 'postgres:13'
  #   container_name: progig-postgres
  #   ports:
  #     - '5432:5432'
  #   env_file: /home/azureuser/environments/.env
  #   volumes:
  #     - ./data/postgres/:/var/lib/postgresql/data/:rw

  # mysql:
  #   image: mysql:latest
  #   container_name: progig-mysql
  #   volumes:
  #     - ./data/mysql/:/var/lib/mysql
  #     - ./data/mysql/initdb.d:/docker-entrypoint-initdb.d
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password123 # any random string will do
  #     MYSQL_DATABASE: progig # the name of your mysql database
  #     MYSQL_USER: shahan # the name of the database user
  #     MYSQL_PASSWORD: password123 # the password of the mysql user
  #   ports:
  #     - '3300:3306'

volumes:
  progig-backend: {}
