version: '3.3'
services:
  backend-dev:
    build:
      context: .
    command: npm run start:dev
    container_name: progig-backend-dev
    env_file: /home/azureuser/environments/.env.development
    ports:
      - '3010:3010'
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
