# -------------------------------------- #
# --------------- INPUT ---------------- #
# -------------------------------------- #

############ USER ###########

input RegistrationInput {
  first_name: String!
  last_name: String!
  email: String!
  password: String!
  role: UserRole!
}

type User {
  id: ID
  first_name: String
  last_name: String
  email: String
  role: UserRole
  is_email_verified: Boolean
  created_at: String
  updated_at: String
}

type LoginResponse {
  success: Boolean
  message: String
  user: User
  token: String
}

type RegistrationResponse {
  success: Boolean
  message: String
  user: User
}
